# https://taskfile.dev
version: '2'
tasks:
  run:
    cmds:
      - mix phx.server
      #- iex -S mix phx.server
  sh:
    cmds:
      - iex -S mix
  test:
    cmds:
      - mix test
  
  fmt:
    cmds:
      - mix format
      
  open:
    cmds:
      - open http://localhost:4000
      # great live dashboard
      # - open http://localhost:4000/dashboard
  db-mig:
    cmds:
      - mix ecto.reset # --no-start
  sql:
    cmds:
      - mycli -uroot hello_dev

  # mix help --search "phx"

  routes:
    cmds:
      - mix phx.routes

  stack:
    cmds:
      - asdf current
      - elixir -v
      - mix phx.new -v # --version

  setup:
    cmds:
      # elixir by asdf
      - mix local.hex
      - mix local.phx

  create-hello:
    desc: create hello project by https://hexdocs.pm/phoenix/up_and_running.html#content
    cmds:
      # https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html
      - mix phx.new hello --database mysql --verbose
      - |
        cd hello
        mix ecto.create