# https://taskfile.dev
version: '2'
tasks:
  run:
    cmds:
      - mix phx.server
      #- iex -S mix phx.server
  sh:
    cmds:
      - iex -S mix
  test:
    cmds:
      - mix test
  
  fmt:
    cmds:
      - mix format
      
  open:
    cmds:
      - open http://localhost:4000
      # great live dashboard
      # - open http://localhost:4000/dashboard
  db-mig:
    cmds:
      - mix ecto.reset # --no-start
  sql:
    cmds:
      - mycli -uroot hello_dev

  # mix help --search "phx"

  routes:
    cmds:
      - mix phx.routes
  
  local-prod-db:
    desc: prepare local prod db
    env:
      # mix phx.gen.secret
      SECRET_KEY_BASE: "xX+7kG+1kU0/LmKJEFcMCia+iLmhztf3BO+6taJGWE38Cm7My4PgcWtMRibrIy0X"
      DATABASE_URL: ecto://root:@localhost/hello_phx_prod
    cmds:
      - MIX_ENV=prod mix ecto.setup

  local-prod:
    desc: run phx server in production mode
    env:
      SECRET_KEY_BASE: "xX+7kG+1kU0/LmKJEFcMCia+iLmhztf3BO+6taJGWE38Cm7My4PgcWtMRibrIy0X"
      DATABASE_URL: ecto://root:@localhost/hello_phx_prod
      STATIC_HOST_PORT: 4010
    cmds:
      - |
        echo prod env:
        echo SECRET_KEY_BASE=${SECRET_KEY_BASE}
        echo DATABASE_URL=${DATABASE_URL}
        echo STATIC_HOST_PORT=${STATIC_HOST_PORT}
      - |
        # Initial setup
        mix deps.get --only prod
        MIX_ENV=prod mix compile

        # Compile assets
        npm run deploy --prefix ./assets
        mix phx.digest

        # Custom tasks (like DB migrations)
        MIX_ENV=prod mix ecto.migrate

        # Finally run the server
        PORT=4001 MIX_ENV=prod mix phx.server
        # in detached mode
        # PORT=4001 MIX_ENV=prod elixir --erl "-detached" -S mix phx.server
        # in iex shell
        # PORT=4001 MIX_ENV=prod iex -S mix phx.server

  stack:
    cmds:
      - asdf current
      - elixir -v
      - mix phx.new -v # --version

  setup:
    cmds:
      # elixir by asdf
      - mix local.hex
      - mix local.phx

  create-hello:
    desc: create hello project by https://hexdocs.pm/phoenix/up_and_running.html#content
    cmds:
      # https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html
      - mix phx.new hello --database mysql --verbose
      - |
        cd hello
        mix ecto.create